Scala object serializer supports copying.
altoo-ag/scala-kryo-serialization pull request #16
Opened 2024-09-25 20:36 UTC by sageserpent-open

This follows on from https://github.com/altoo-ag/akka-kryo-serialization/issues/297.

I've broken up the PR into three commits.

1. Add a test for the existing serialization / deserialization functionality provided by `ScalaObjectSerializer`.
2. Add a failing test to reproduce the problem with copying.
3. Make the failing test pass.

2024-09-25 20:37 UTC, sageserpent-open commented
Oh drat - I had to push to a fork of this repository, so could someone approve the failing CI workflow run, please?

2024-09-26 07:25 UTC, sageserpent-open commented
Thanks @danischroeter for triggering the workflow run.

Unfortunately it failed when building for Scala 2.12; I've pushed a new commit (and this time, I ran the full cross build locally, lesson learned).

Would you trigger the CI workflow again when you have a moment?

2024-09-26 08:32 UTC, sageserpent-open commented
@danischroeter This is odd - the CI build is still failing, but with this error:

```text
Run sbt +test
/home/runner/work/_temp/b0abd[6](https://github.com/altoo-ag/scala-kryo-serialization/actions/runs/11047497892/job/30690517455#step:4:7)a0-fd9d-426f-b3c2-0542eb49ae20.sh: line 1: sbt: command not found
Error: Process completed with exit code 12
```
[7](https://github.com/altoo-ag/scala-kryo-serialization/actions/runs/11047497892/job/30690517455#step:4:8).

I've not changed any of the workflow configuration in this PR, so I assume this is either a transient glitch - perhaps due to the node switch from node12 to node16?

Other than asking you to re-trigger again, I'm not sure what to do. If this failure is repeatble, then perhaps running the CI action on branch `main` might help diagnose what's wrong?

2024-09-26 08:44 UTC, danischroeter commented
Jep I already created another issue... #17

2024-09-26 08:51 UTC, sageserpent-open commented
I tried re-triggering the CI build on the Americium repository, this uses a later version of `setup-java` step.

It's working nicely right now, finding SBT.

An excerpt:

```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt +test
```

2024-09-26 09:52 UTC, sageserpent-open commented
@danischroeter I took the liberty of upgrading the GitHub workflow steps to v4 for checkout and Java setup.

I don't know whether you folks have strong feelings about sticking with v2, but if you're happy with the upgrade being bundled in with this PR, please re-trigger the CI build.

If not, let me know and I'll `git reset --hard` on the PR branch and force-push to remove commit f7887cc.

2024-09-26 10:00 UTC, sageserpent-open commented
Drat - I only cutover the `fullTest.yml` workflow - I've force-pushed to include the `pullCI.yml` as well.

Another re-trigger, please... 😅

2024-09-26 11:10 UTC, danischroeter commented
@sageserpent-open thx for the effort!
still did not work - will try to fix this in a separate pr and then resume here...
just need to get a few other things done first.

2024-09-26 13:05 UTC, danischroeter commented
@sageserpent-open 
#17 is fixed :) - `ubuntu-latest` was the *problem* 
can you rebase pls?

2024-09-26 13:42 UTC, sageserpent-open commented
@danischroeter Excellent, thanks.

I've rebased and force-pushed. Would you trigger the build again, please...

2024-09-26 14:21 UTC, danischroeter requested changes
Nice thx - just one small testing improvement.

2024-09-26 15:13 UTC, sageserpent-open commented on core/src/test/scala/io/altoo/serialization/kryo/scala/testkit/AbstractKryoTest.scala
> +  protected final def testCopyingOf[T](obj: T): T = {
Yes, I was aware of this from writing the test for round-tripping of singletons - that uses the existing `testSerializationOf` helper, and that too uses plain universal equality `==`.

In both cases, because the singleton objects passed to either `testSerializationOf` or `testCopyingOf` don't customise equality, the fallback of identity comparison is what's really being asserted here, albeit implicitly.

I agree that it isn't immediately apparent that this is the case, but am not completely sure what exactly we should set as our test expections here. Consider serializing in one process and deserializing in another - the whole notion of preserving object identity vanishes, although I think its entirely reasonable not to try to serialize the original singleton's state and then resurrect it as a brand new instance distinct from whatever corresponding singleton exists in the deserializing process. All the more so if the latter process has a different layout / implementation due to code changes.

How about this as a compromise? Both helpers return the round-tripped / copied instance, so we could keep the assertions as they are in both places, but change the calling test to make a stronger identity assertion. Going further, the singletons could then define a state-based equality, so the overall test checks first that state is preserved via the helpers, then goes further and checks that identity is preserved for singletons.

I can push out a commit to show what I mean, if you're not happy we can either modify it or `git revert --hard` and try something completely different...

2024-09-26 15:31 UTC, sageserpent-open commented on core/src/test/scala/io/altoo/serialization/kryo/scala/testkit/AbstractKryoTest.scala
> +  protected final def testCopyingOf[T](obj: T): T = {
Updated in 09e1485.

2024-09-26 15:34 UTC, danischroeter commented on core/src/test/scala/io/altoo/serialization/kryo/scala/testkit/AbstractKryoTest.scala
> +  protected final def testCopyingOf[T](obj: T): T = {
lgtm! thx

2024-09-26 15:35 UTC, danischroeter approved these changes

2024-09-26 15:36 UTC, merged

2024-09-26 15:42 UTC, danischroeter commented
@sageserpent-open thx for your contribution! We planned to do a release of scala-kryo-serialization in ~ 2weeks when doing upgrades also for pekko 1.1. Or if it's very crucial for you we can do a release for your change...

2024-09-26 17:11 UTC, sageserpent-open commented
@danischroeter, it was pleasure working with you folks. I’m in no hurry - got a workaround in place, just wanted to contribute the fix upstream. I’ll keep an eye out for your next release. 

Cheers for now…